// leaderboardData.js
export const leaderboardData = {
    math: [
        // Top 3 with exceptional styling
        {
            id: 1,
            name: "John Doe",
            rank: 1,
            institute: "Harvard University",
            score: 98,
            time: "1:23:45",
            image: "https://randomuser.me/api/portraits/men/1.jpg",
            attempts: 12,
            completion: "100%",
        },
        {
            id: 2,
            name: "Jane Smith",
            rank: 2,
            institute: "Stanford University",
            score: 95,
            time: "1:25:12",
            image: "https://randomuser.me/api/portraits/women/1.jpg",
            attempts: 10,
            completion: "98%",
        },
        {
            id: 3,
            name: "Alex Johnson",
            rank: 3,
            institute: "MIT",
            score: 93,
            time: "1:26:33",
            image: "https://randomuser.me/api/portraits/men/2.jpg",
            attempts: 9,
            completion: "96%",
        },
        // Regular entries
        {
            id: 4,
            name: "Sarah Williams",
            rank: 4,
            institute: "Cambridge University",
            score: 90,
            time: "1:28:45",
            image: "https://randomuser.me/api/portraits/women/2.jpg",
            attempts: 8,
            completion: "94%",
        },
        {
            id: 5,
            name: "Michael Brown",
            rank: 5,
            institute: "Oxford University",
            score: 88,
            time: "1:30:12",
            image: "https://randomuser.me/api/portraits/men/3.jpg",
            attempts: 7,
            completion: "92%",
        },
        {
            id: 6,
            name: "Emily Davis",
            rank: 6,
            institute: "Yale University",
            score: 85,
            time: "1:32:33",
            image: "https://randomuser.me/api/portraits/women/3.jpg",
            attempts: 6,
            completion: "90%",
        },
        {
            id: 7,
            name: "David Wilson",
            rank: 7,
            institute: "Princeton University",
            score: 82,
            time: "1:35:45",
            image: "https://randomuser.me/api/portraits/men/4.jpg",
            attempts: 5,
            completion: "88%",
        },
        {
            id: 8,
            name: "Olivia Taylor",
            rank: 8,
            institute: "Columbia University",
            score: 80,
            time: "1:38:12",
            image: "https://randomuser.me/api/portraits/women/4.jpg",
            attempts: 5,
            completion: "85%",
        },
        {
            id: 9,
            name: "James Anderson",
            rank: 9,
            institute: "University of Chicago",
            score: 78,
            time: "1:40:33",
            image: "https://randomuser.me/api/portraits/men/5.jpg",
            attempts: 4,
            completion: "82%",
        },
        {
            id: 10,
            name: "Sophia Martinez",
            rank: 10,
            institute: "Caltech",
            score: 75,
            time: "1:42:45",
            image: "https://randomuser.me/api/portraits/women/5.jpg",
            attempts: 4,
            completion: "80%",
        },
        {
            id: 11,
            name: "Robert Thomas",
            rank: 11,
            institute: "ETH Zurich",
            score: 72,
            time: "1:45:12",
            image: "https://randomuser.me/api/portraits/men/6.jpg",
            attempts: 3,
            completion: "78%",
        },
        {
            id: 12,
            name: "Emma Garcia",
            rank: 12,
            institute: "University of Tokyo",
            score: 70,
            time: "1:48:33",
            image: "https://randomuser.me/api/portraits/women/6.jpg",
            attempts: 3,
            completion: "75%",
        },
        {
            id: 13,
            name: "William Rodriguez",
            rank: 13,
            institute: "National University of Singapore",
            score: 68,
            time: "1:50:45",
            image: "https://randomuser.me/api/portraits/men/7.jpg",
            attempts: 3,
            completion: "72%",
        },
    ],
    science: [
        {
            id: 1,
            name: "Ava Lopez",
            rank: 1,
            institute: "Peking University",
            score: 65,
            time: "1:53:12",
            image: "https://randomuser.me/api/portraits/women/7.jpg",
            attempts: 2,
            completion: "70%",
        },
        {
            id: 2,
            name: "Benjamin Hernandez",
            rank: 2,
            institute: "University of Toronto",
            score: 63,
            time: "1:55:33",
            image: "https://randomuser.me/api/portraits/men/8.jpg",
        },
        {
            id: 3,
            name: "Mia Clark",
            rank: 3,
            institute: "University of Melbourne",
            score: 60,
            time: "1:58:45",
            image: "https://randomuser.me/api/portraits/women/8.jpg",
            attempts: 2,
            completion: "70%",
        },
    ],
    biology: [
        {
            id: 1,
            name: "Liam Walker",
            rank: 1,
            institute: "University of California, Berkeley",
            score: 58,
            time: "2:00:12",
            image: "https://randomuser.me/api/portraits/men/9.jpg",
            attempts: 2,
            completion: "70%",
        },
        {
            id: 2,
            name: "Charlotte Hall",
            rank: 2,
            institute: "University of Oxford",
            score: 55,
            time: "2:02:33",
            image: "https://randomuser.me/api/portraits/women/9.jpg",
            attempts: 2,
            completion: "68%",
        },
        {
            id: 3,
            name: "Elijah Young",
            rank: 3,
            institute: "University of Cambridge",
            score: 53,
            time: "2:05:45",
            image: "https://randomuser.me/api/portraits/men/10.jpg",
            attempts: 2,
            completion: "65%",
        },
        {
            id: 4,
            name: "Isabella King",
            rank: 4,
            institute: "University of Edinburgh",
            score: 50,
            time: "2:08:12",
            image: "https://randomuser.me/api/portraits/women/10.jpg",
            attempts: 2,
            completion: "63%",
        },
    ],
};

export const exams = [
    { id: "math", name: "Mathematics Olympiad" },
    { id: "science", name: "Science Challenge" },
    { id: "biology", name: "Biology Competition" },
];
